### PR TITLE
🎨 Initial pass on window manager theming

### PR DESCRIPTION
**Pull request by trickypr**
This pull request contains the initial theme for the dotOS DE. It only contains a light theme, but should be able to be adapted to a dark theme with a few scripts. This is only an initial first pass, meaning that the icons and padding need refinement. 
image

### IceWM rather than openbox
When developing for openbox, I ran into the limitations of its theming system. Openbox doesn't have any support for rounded corners. IceWM contains a system where you can put whatever [images you want](https://ice-wm.org/themes/#frames) around each window allowing you to hack together rounded corners that work on any program. 

## Known issues
GTK applications do not play nice with this theme at this point in time. Presumably this could be fixed with some tweaks to either this theme or to the gtk theme.
image

### CODE REVIEW

**Comment by EnderDev** [comment]
I’ve noticed the bar at the bottom, can that only be modified through the window manager? Or do you think we could add a bar in the desktop environment UI that just manipulates the windows?

**Comment by EnderDev** [comment]
Another thing, the rounded edges on the windows look very rough 
94D1E784-AD21-44F7-9970-24999104C66E

**Comment by trickypr** [comment]
Maybe it would be a better idea for me to be rounding the corners in picom, so I get anti-aliasing. 

The current task bar can only be manipulated through the window manager, but can be disabled with the `ShowTaskBar = 0` theme option. When we have a proper panel ui, we can sub it in.

**Comment by trickypr** [comment]
I have re-implemented the window rounding in picom and the roughness is mostly gone (although it is a bit laggy when moving windows, probably because my vm's hardware acceleration doesn't seem to work).
image

**Pull request merged**
